---
- name: Prepare OpenLDAP
  hosts: openldap
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: include global settings
      include_vars: group_vars/all
    - name: Show OpenLDAP info
      debug: var=hostvars[inventory_hostname]
      when: debug
  roles:
    - openldap
